# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20171122_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL名称'),
        ),
    ]
