# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20171122_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('host_add', '新增主机'), ('host_del', '删除主机'), ('project_add', '新增项目'), ('project_del', '删除项目'), ('project_edit', '编辑项目'), ('project_task_add', '新增任务'), ('project_task_del', '删除任务'), ('project_task_edit', '编辑任务')), 'verbose_name': '权限表', 'verbose_name_plural': '权限表'},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='argument_list',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='name',
        ),
        migrations.AddField(
            model_name='permission',
            name='codename',
            field=models.CharField(default='ahaha', max_length=64, verbose_name='权限码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='describe',
            field=models.CharField(max_length=255, verbose_name='权限描述'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL路径'),
        ),
    ]
