# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20171123_1045'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='sys_perm',
        ),
    ]
