# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('system', '0005_auto_20171123_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='content_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
