# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名')),
                ('type', models.CharField(max_length=10, verbose_name='项目类型')),
                ('desc', models.TextField(verbose_name='项目描述')),
                ('path', models.CharField(max_length=10, verbose_name='项目路径')),
                ('package_name', models.CharField(max_length=20, verbose_name='包名')),
                ('on_work', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pm_project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='任务名')),
                ('desc', models.TextField(verbose_name='任务描述')),
                ('type', models.CharField(max_length=10, verbose_name='任务类型')),
                ('script', models.TextField(verbose_name='任务脚本')),
            ],
            options={
                'db_table': 'pm_task',
            },
        ),
    ]
