# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='path',
            field=models.CharField(max_length=100, verbose_name='项目路径'),
        ),
    ]
